# Generated by Django 4.2.2 on 2023-07-03 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='name',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='register',
            name='password',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='register',
            name='phone_num',
            field=models.IntegerField(),
        ),
    ]
