# Generated by Django 4.2.3 on 2023-07-14 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_name', models.CharField(max_length=250)),
                ('emp_id', models.CharField(max_length=250)),
                ('emp_dept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to='app1.department')),
            ],
        ),
    ]
